apiVersion: v1.edp.epam.com/v1
kind: Keycloak
metadata:
  name: keycloak-sample
spec:
  secret: my-keycloak-secret
  url: https://example.com
  caCertificateRef:
    kind: Secret
    name: custom-ca
    key: ca.crt